### ISSUE TITLE
Inference from management console not working on Kubernetes

### ISSUE THREAD

**Issue by EvenAR** [deepjavalibrary/djl-serving#1204]
## Description

I'm hosting DJL Serving and the management console using `bin\serving.bat` on Kubernetes which forwards incoming traffic from port 8443 (https) to the `inference_address` and `management_address`. 

When making an inference request from the UI, the `inference_address`' port number is appended to my hostname (e.g. https://mydomain.com:8080) causing the request to fail. Is this a bug or am I missing some configuration?

My `config.properties`:
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8080
cors_allowed_origin=https://mydomain.com
cors_allowed_methods=*
cors_allowed_headers=*
```

Making a curl from a terminal works as expected: `curl https://mydomain.com/predictions/my_model -T image.jpg`

### Expected Behavior

When I try to run inference from the management console the request should be sent to `https://mydomain.com/predictions/my_model/`

### Error Message

The request is sent to `https://mydomain.com:8080/predictions/my_model/` ending with a request timeout.

### Steps to reproduce

Download https://publish.djl.ai/djl-serving/serving-0.22.1.zip and run `serving-0.22.1\bin\serving.bat` from a Debian-slim-container with JDK installed.

**Comment by frankfliu** [comment]
@EvenAR 

I don't think DJLServing works for this use case today. DJLServing allows management and inference listen on different port. Currently console will query the management API to get inference port. However, if you map the port, this behavior will break.

I think there is a few thing we can do:
1. If management port and inference port are the same, instead of using DJLServing port, we can use the mapped port (current port by browser)
2. If they are different, we can add a config page in console and let user input the inference port

Are you interested to contribute to this improvement?
