### ISSUE TITLE
is there any instruction for parsing customized paramters  of REST API ?

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl-serving#260]
I load my model on djl-serving and the paramters should be a float[4] array or a specific class。

In demo i just override processInput() and processOutput()，because the class of input  is a customized class。

But in djl-serving I don't how to parse paramters into "input". I saw maybe some code should be configured in .yml file. 
 
so is there any instruction for parse customized paramters into input?

**Comment by frankfliu** [comment]
The DJL REST API is pretty flexible, you can send parameters using:
1. query string (?param1=xxx&param2=xxx)
2. multipart/form-data
3. application/x-www-form-urlencoded
4. any POST body

The whole HTTP request will be parsed into single `ai.djl.modality.Input` object. HTTP headers will be saved in `Input.properties` field.
In case of query string, multipart/form-data and application/x-www-form-urlencoded, each request parameter and its value will be stored in `Input.content`. otherwise the request body will be store as byte[] in `Input.content` field.

For a custom model, you need provide a Translator<Input, Output>, and it's up to you to read the byte[] and deserialize to proper java object.

The `Input` class provides a few helper functions to make it easy to decode common data:
1. `getAsString(0)` - decode the POST body as String, then you parse to json in your Translator if the input is a json string
2. `getDataAsNDList()` - decode the POST body as `NDList` object
3. `getAsNDArray()` - decode the POST body into a single `NDarry`
4. `getAsBytes()` - get raw byte[] of the body

In your case, you can:
1. encode your `float[]` into json, and post the json as HTTP body
2. encode your `float[]` into byte[] and sent the binary data in HTTP body
3. encode your `float[]` into comma delimited string and send as parameter
